### ISSUE TITLE
Deserializing model fit with GPU onto machine using CPU

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#37]
I've fit a model on a GPU machine, and serialized it with `save_model` and am now wanting to deserialize it on a machine without a GPU for making some predictions. However, when I do this via `TabularModel.load_from_checkpoint`, I get the following:

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 
If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') 
to map your storages to the CPU.
```

Unfortunately there appears to be no way of passing arguments to `load_from_checkpoint` that get passed to `torch.load`. Is there a workaround for this? I would imagine this would be a relatively common scenario--fitting a model on a GPU and then using it elsewhere?

Running pytorch_tabular 0.6.0 and pytorch 1.8.0

**Comment by manujosephv** [comment]
Sorry @fonnesbeck  Was quite held up by my day job. And unfortunately, this is currently not possible. It's a simple fix though. the capability is there in PyTorch Lightning, but not exposed in PyTorch Tabular api.

Will need to take in an additional parameter in [load_from_checkpoint ](https://github.com/manujosephv/pytorch_tabular/blob/f83019a4fa964caece88e2757b78e2789ada0927/pytorch_tabular/tabular_model.py#L712) and pass on that parameter as map_location [here](https://github.com/manujosephv/pytorch_tabular/blob/f83019a4fa964caece88e2757b78e2789ada0927/pytorch_tabular/tabular_model.py#L756)

As soon as I get some time, I'll make the change and push to develop branch

**Comment by fonnesbeck** [comment]
Thanks! If I get some time this weekend I can try and submit a PR.

**Comment by manujosephv** [comment]
I have included this change and pushed a new update. Can you check if that works now?

**Comment by fonnesbeck** [comment]
It does work, based on a simple test. Thanks again!
